FROM php:8.3-cli

RUN apt-get update && apt-get install -y \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    git \
    curl \
    libzip-dev

RUN docker-php-ext-install pdo_mysql mbstring zip

WORKDIR /app
COPY . /app

RUN chmod -R 777 /app/storage /app/bootstrap/cache

EXPOSE 8000
CMD sh -c "php artisan migrate --force --seed && php artisan serve --host=0.0.0.0 --port=8000"
