FROM php:8.4-cli

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN apt-get update && apt-get install -y \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    git \
    curl \
    libzip-dev

RUN docker-php-ext-install pdo_mysql mbstring zip

WORKDIR /app
COPY . /app

# Install PHP dependencies via Composer
RUN composer install --no-dev --optimize-autoloader

RUN chmod -R 777 /app/storage /app/bootstrap/cache

EXPOSE 8000
CMD sh -c "php artisan migrate --force --seed && php artisan serve --host=0.0.0.0 --port=8000"
